config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
   get 'home/about' => 'homes#about',as: 'about'
  resources :books, only: [:new, :index, :show, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  # def after_sign_out_path_for(resource)
  #   about_path
  # end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
    @books = Book.all
    @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),  notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user

  end

  def show
    @book_new = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id),  notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<!--<p id="notice"></p>-->
<!--  <div class="container px-5 px-sm-0">-->
<!--  <div class="row">-->
<!--  <div class="col-md-3">-->
<!--    <h2>User info</h2>-->
<%#= user.name %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	  <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title" %>
        </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <% end %>
        <a><%= link_to "Show", book_path(@book.id) %></a>
      <a>|</a>
    <a><%= link_to "Back", books_path %></a>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <table class='table'>
          <tr><%= image_tag @user.get_profile_image(63,63) %></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>
          <div class='row'>
            <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
            <h2 class="mt-3">New book</h2>
            <%= form_with model: @book do |f| %>
            <div class="form-group">
              <h4>Title</h4>
              <%= f.text_field :title,  class: "form-control"  %>
            </div>
          <div class="form-group">
            <h4>Opinion</h4>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(@user.get_profile_image(40,40)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id)  %></td>
              <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
        <h2>User info</h2>
          <table class='table'>
            <tr><%= image_tag @user.get_profile_image(63,63) %></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </table>
            <div class='row'>
              <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
                <i class="fas fa-user-cog"></i>
              <% end %>
          </div>
        <h2 class="mt-3">New book</h2>
          <%= form_with model: @book_new, url: books_path, method: :post do |f| %>
            <div class="form-group">
              <h4>Title</h4>
                <%= f.text_field :title,  class: "form-control"  %>
            </div>
          <div class="form-group">
              <h4>Opinion</h4>
            <%= f.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
                <% end %>
          </div>
          <div class="col-md-8 offset-md-1">
  		  <h2>Book detail</h2>
  		    <table class="table">
  		      <tbody>
  		        <tr>
                <td><%= link_to image_tag(@user.get_profile_image(40,40)), user_path(@user) %>
                <br /><%= link_to @user.name, user_path(@user) %>
                </td>
                <td><%= link_to @book.title, book_path(@book.id)  %></td>
                <td><%= @book.body %></td>
                <% if @user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                <% end %>
              </tr>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
  <body>
    <header>
</header>
      <main>
        <p id="notice"></p>
        <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>
  </body>

app/views/homes/top.html.erb
 <main>
 <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to  new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fas fa-users"></i> Users
                <% end %>
              </li>
               <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if flash[:notice] %>
   <p id="notice">
    <%= flash[:notice] %>
   </p>
  <% end %>
    <%= yield %>
  <footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control name", autofocus: true, id:"inputName" %>
        </div>
        <div class="form-group">
          <label for="profile_Image">Image</label>
          <%= f.file_field :profile_image, class: "form-control-file profile_Image", placeholder: "プロフィール画像", accept: "image/*" %>
        <div class="form-group">
          <label for="user_introduction">Intoroduction</label>
          <%= f.text_area :introduction, class: "form-control introduction", autofocus: true, id:"inputName" %>
        </div>
        <div class="form-group">
          <label><%= f.submit "Update User", class: "btn btn-secondary" %></label>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <table class='table'>
          <tr><%= image_tag @user.get_profile_image(63,63) %></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>
        <div class='row'>
          <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
          <h2 class="mt-3">New book</h2>
            <%= form_with model: @book do |f| %>
            <div class="form-group">
              <h4>Title</h4>
              <%= f.text_field :title,  class: "form-control"  %>
            </div>
            <div class="form-group">
              <h4>Opinion</h4>
              <%= f.text_area :body, class: "form-control" %>
            </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(40,40) %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<main>
    <p id="notice"><% notice %></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <table class='table'>
          <tr><%= image_tag @user.get_profile_image(63,63) %></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>
      <div class='row'>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
    <%= form_with model: @book_new, url: books_path, method: :post do |f| %>
      <div class="form-group">
        <h4>Title</h4>
          <%= f.text_field :title,  class: "form-control"  %>
      </div>
      <div class="form-group">
        <h4>Opinion</h4>
          <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(@user.get_profile_image(40,40)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id)  %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>
</main>